name: 'Running AQA test'
description: 'Running AQA test'
author: 'Sophia Guo'
inputs:
  jdksource:      # AdoptOpenJDK/install-jdk, github-hosted environment, upstream
    description: 'github-hosted default or customized'
    default: 'upstream'
  version:              # jdk version
    description: 'testing jdk version (Required when jdksource is github-hosted or install-jdk.)'
    required: false
  build_list:           # test category
    description: 
    default: 'openjdk'
  target:              # test
    description: 
    default: '_jdk_math'
  custom_target:   #  Used if need to set non-default custom target
    description:
    required: false
  openjdk_testRepo:
    description: 'openjdk-tests Repo'
    required: false
    default: 'aqa-tests:master'
  openj9_repo:
    description: 'openj9 Repo'
    required: false
    default: 'openj9:master'
  tkg_Repo:
    description: 'TKG Repo'
    required: false
    default: 'TKG:master'
  vendor_testRepos:
      description: 'Comma-separated list of vendor repositories'
      required: false
  vendor_testBranches:
      description: 'Comma-separated list of vendor branches'
      required: false
  vendor_testDirs:
      description: 'Comma-separated list of vendor directories'
      required: false
  vendor_testShas:
      description: 'Comma-separated list of vendor SHAs'
      required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
