name: "build-test"
on: # rebuild any PRs and main branch changes
  push:

jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #[ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '11'
        targets: 'JDK_11'
    - name: AQA
      uses: ./
      with: 
        version: '11'
        jdksource: 'install-jdk'
        build_list: 'openjdk'
        target: '_jdk_custom'

        