name: "build-test"
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - feature

jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #[ubuntu-latest, macos-latest]
    env:
      version: '11'
    steps:
    - uses: actions/checkout@v1
    - run: 'wget -P buildJDK https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '${{ env.version }}'
        architecture: x64
        source: './buildJDK/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
        targets: 'JDK_11'
        archiveExtension: '.tar'
    - name: AQA
      uses: AdoptOpenJDK/run-aqa@v1
      with:
        version: '${{ env.version }}'
        jdksource: 'customized'
        build_list: 'openjdk'
        target: '_jdk_custom'


#  name: "test updated installJDK with AdoptOpenJDK/install-jdk, using set-env "
#  on: # rebuild any PRs and main branch changes
#    push:
   
#  jobs:
#    build: # make sure build/ci work properly
#      runs-on: ${{ matrix.os }}
#      strategy:
#        fail-fast: false
#        matrix:
#          os: [ubuntu-latest] #[ubuntu-latest, macos-latest]
#      steps:
#        - uses: actions/checkout@v1
#        - run: 'wget -P buildJDK https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
#        - run: echo "::set-env name=version::11"
#        - uses: AdoptOpenJDK/install-jdk@v1
#          with:
#            version: '${{ env.version }}'
#            architecture: x64
#            source: './buildJDK/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
#            targets: 'JDK_11'
#            archiveExtension: '.tar'
#        - name: AQA
#          uses: AdoptOpenJDK/run-aqa@v1
#          with:
#            version: '${{ env.version }}'
#            jdksource: 'customized'
#            build_list: 'openjdk'
#            target: '_jdk_custom' 

#  name: "test updated installJDK with AdoptOpenJDK/install-jdk, using env"
# test: https://github.com/sophia-guo/runaqaTest/runs/512036800?check_suite_focus=true
#  on: # rebuild any PRs and main branch changes
#    push:
   
#  jobs:
#    build: # make sure build/ci work properly
#      runs-on: ${{ matrix.os }}
#      strategy:
#        fail-fast: false
#        matrix:
#          os: [ubuntu-latest] #[ubuntu-latest, macos-latest]
#      env:
#        version: '11'
#      steps:
#        - uses: actions/checkout@v1
#        - run: 'wget -P buildJDK https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
#        - uses: AdoptOpenJDK/install-jdk@v1
#          with:
#            version: '${{ env.version }}'
#            architecture: x64
#            source: './buildJDK/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
#            targets: 'JDK_11'
#            archiveExtension: '.tar'
#        - name: AQA
#          uses: AdoptOpenJDK/run-aqa@v1
#          with:
#            version: '${{ env.version }}'
#            jdksource: 'customized'
#            build_list: 'openjdk'
#            target: '_jdk_custom'  


#  name: "test DK generated by buildJDK action, first test with http://"
#  test result: https://github.com/sophia-guo/runaqaTest/runs/506263155?check_suite_focus=true
# TODO: feature requirement for installJDK action: nice to have parameters be core.setOutput ['version', 'architecture', 'archiveExtension']
#  on: # rebuild any PRs and main branch changes
#    push:
   
#  jobs:
#    build:
#      runs-on: ${{ matrix.os }}
#      strategy:
#        fail-fast: false
#        matrix:
#          os: [ubuntu-latest] #[ubuntu-latest, macos-latest]
#      steps:
#      - uses: actions/checkout@v1
#      - uses: TheMrMilchmann/install-jdk@v1
#        // id: installJDK
#        with:
#          version: '11'
#          architecture: x64
#          source: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
#          targets: 'JDK_11'
#          archiveExtension: '.tar'
#      - name: AQA
#        uses: AdoptOpenJDK/run-aqa@v1
#        with: 
#          version: '11'  //${{ steps.installJDK.outputs.version }}
#          jdksource: 'customized'
#          build_list: 'openjdk'
#          target: '_jdk_custom'


#  name: "test local JDK generated by buildJDK action, simulate by download jdk to specifc path"
#  test result: https://github.com/sophia-guo/runaqaTest/runs/506375528?check_suite_focus=true
#  TODO: feature requirement for buildJDK action: nice to have build parameters be core.setOutput ['version', 'architecture', 'archiveExtension']
#  on: # rebuild any PRs and main branch changes
#    push:
   
#  jobs:
#    build:
#      runs-on: ${{ matrix.os }}
#      strategy:
#        fail-fast: false
#        matrix:
#          os: [ubuntu-latest] #[ubuntu-latest, macos-latest]
#      steps:
#      - uses: actions/checkout@v1
#      - run: 'wget -P buildJDK https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
#      - uses: AdoptOpenJDK/install-jdk@v1
#        with:
#          version: '11' // ${{ steps.buildJDK.outputs.version }}
#          architecture: x64
#          source: './buildJDK/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
#          targets: 'JDK_11'
#          archiveExtension: '.tar'
#      - name: AQA
#        uses: AdoptOpenJDK/run-aqa@v1
#        with: 
#          version: '11' // ${{ steps.buildJDK.outputs.version }}
#          jdksource: 'customized'
#          build_list: 'openjdk'
#          target: '_jdk_custom'  

# TODO example:
#  name: "test local JDK generated by buildJDK action, with outputs buildjdk name and directory" or using enviromental variables
# 
#  TODO: feature requirement for buildJDK action: nice to have build parameters be core.setOutput ['version', 'architecture', 'archiveExtension']
#  on: # rebuild any PRs and main branch changes
#    push:
   
#  jobs:
#    build:
#      runs-on: ${{ matrix.os }}
#      strategy:
#        fail-fast: false
#        matrix:
#          os: [ubuntu-latest] #[ubuntu-latest, macos-latest]
#      steps:
#      - uses: actions/checkout@v1
#      - uses: AdoptOpenJDK/run-build@v1
#        id: 'buildjdk'
#        with:
#          version: '11'
#          architecture: x64
#      - uses: AdoptOpenJDK/install-jdk@v1
#        with:
#          version: '11' // ${{ steps.buildjdk.outputs.version }}
#          architecture: x64 // ${{ steps.buildjdk.outputs.architecture }}
#          source: './buildJDK/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz' // '${{ steps.buildjdk.outputs.direcotry}}/${{steps.buildjdk.outputs.jdkname }}'
#          targets: 'JDK_11'
#          archiveExtension: '.tar' // ${{steps.buildjdk.outputs.archiveExtension}}
#      - name: AQA
#        uses: AdoptOpenJDK/run-aqa@v1
#        with: 
#          version: '11' // ${{ steps.buildjdk.outputs.version }}
#          jdksource: 'customized'
#          build_list: 'openjdk'
#          target: '_jdk_custom'  